spring:
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  profiles:
    default: local
  application:
    name: ledgerbank
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: OPENAPI_3_0
  paths-to-match: /api/v1/**
  override-with-generic-response: false
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
ledgerbank:
  auth:
    session-ttl: ${AUTH_SESSION_TTL:PT8H}
  idempotency:
    transfer-ttl: ${TRANSFER_IDEMPOTENCY_TTL:PT24H}
    lock-ttl: ${TRANSFER_IDEMPOTENCY_LOCK_TTL:PT30S}
  bootstrap-admin:
    email: ${APP_ADMIN_EMAIL:}
    password: ${APP_ADMIN_PASSWORD:}
