spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5433/ledgerbank_test}
    username: ${TEST_DB_USERNAME:ledgerbank}
    password: ${TEST_DB_PASSWORD:ledgerbank}
    hikari:
      connection-init-sql: SET lock_timeout = '5s'
  data:
    redis:
      host: ${TEST_REDIS_HOST:localhost}
      port: ${TEST_REDIS_PORT:6380}
      password: ${TEST_REDIS_PASSWORD:ledgerbank}
      repositories:
        enabled: false
  rabbitmq:
    host: ${TEST_RABBITMQ_HOST:localhost}
    port: ${TEST_RABBITMQ_PORT:5673}
    username: ${TEST_RABBITMQ_USERNAME:ledgerbank}
    password: ${TEST_RABBITMQ_PASSWORD:ledgerbank}
    listener:
      simple:
        auto-startup: false
