spring:
  application:
    name: ledgerbank
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledgerbank}
    username: ${DB_USERNAME:ledgerbank}
    password: ${DB_PASSWORD:ledgerbank}
    hikari:
      connection-init-sql: SET lock_timeout = '5s'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: OPENAPI_3_0
  paths-to-match: /api/v1/**
  override-with-generic-response: false
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
